SVA-270 navigation and profile cleanup
Scottish-Tech-Army/Volunteer-app pull request #126
Opened 2023-03-17 11:32 UTC by treneff

- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- Removed home and events buttons from navigation
- replaced profile nav button with settings nav button and it's corresponding icon 
- removed splash screen option and changed welcome screen text in profile screen to Settings.

Fixes # SVA-270

## Type of change

Please delete options that are not relevant

- [] New Feature (non-breaking change which adds functionality)

# Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2023-03-17 13:09 UTC, joefhall requested changes
Thanks @treneff!  Just a couple of comments it would be great if you can look at

2023-03-18 20:42 UTC, treneff commented on app/src/NativeBase/Containers/ProfileContainer.tsx
> +  // const onChangeSplash = ({ welcome, show }: Partial<WelcomeState>) => {
Sorted

2023-03-18 20:44 UTC, treneff commented on app/src/NativeBase/Assets/Fonts/icomoon.ttf
Files amended to be exactly like previous state before the PR, but still show as if they have been changed.

2023-03-19 12:28 UTC, joefhall commented on app/src/NativeBase/Assets/Fonts/icomoon.ttf
Thanks @treneff  I think the reason those 3 files are still showing in the PR is because they've had their permissions changed (that's the "100644 → 100755" next to the filename in the PR 'Files changed' list).  If you `chmod` them back to 644 locally then push the changes, hopefully they should disappear from the PR.

2023-03-21 19:25 UTC, joefhall approved these changes
Good stuff, thanks @treneff ! 👍

2023-03-29 15:03 UTC, DougieWougie approved these changes
I've added any files that have had functionality commented out to [Notion](https://www.notion.so/Engineering-Wiki-17642c46c5ef420289b34500c184c20b) so we don't lose track of it.

Thanks @treneff !

2023-03-31 14:36 UTC, merged