SVA-316 reformat links in the project descriptions
Scottish-Tech-Army/Volunteer-app pull request #163
Opened 2023-05-30 21:17 UTC by PammyLo

- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- In the description some urls and emails are wrapped in square brackets. 
- These code updates finds them, removes the unwanted characters from the weblinks, and makes them clickable hyperlinks. 
- Email addresses are removed (sensitive and unnecessary).  

## Type of change

Please delete options that are not relevant

- [X] Bug fix (non-breaking change which fixes an issue)
- [] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Testing locally

- run the app locally and check the links no longer have unwanted characters 

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2023-06-02 14:52 UTC, CatMac228 commented
Hey @PammyLo not seeing any issues with the Airtable api key 🎉 this is how the links are displaying in my build 
<img width="279" alt="Screenshot 2023-06-02 at 15 52 29" src="https://github.com/Scottish-Tech-Army/Volunteer-app/assets/87582782/9273b85b-30a3-47b6-83d8-fc02e0e6ad3a">

2023-06-02 18:38 UTC, PammyLo commented
> Hey @PammyLo not seeing any issues with the Airtable api key 🎉 this is how the links are displaying in my build <img alt="Screenshot 2023-06-02 at 15 52 29" width="279" src="https://user-images.githubusercontent.com/87582782/242917914-9273b85b-30a3-47b6-83d8-fc02e0e6ad3a.png">

**Thank you so much for testing that @CatMac228! Much appreciated :)** 

I still have the Airtable auth issue, but the clean up code is working, this is now how it arrives in Airtable:
![image](https://github.com/Scottish-Tech-Army/Volunteer-app/assets/52379979/9bb93cbb-09db-4490-a5a8-2b3347229e55)

To see this in the simulators start api with npm start --reset-cache.

2023-06-05 08:13 UTC, CatMac228 commented
Hey @PammyLo 😊 Just wanted to double check before approving - are the square brackets around the URLs expected? 
<img width="288" alt="Screenshot 2023-06-05 at 09 11 52" src="https://github.com/Scottish-Tech-Army/Volunteer-app/assets/87582782/b4ce1db3-a391-4320-af34-c3e93188e328">

2023-06-05 18:30 UTC, PammyLo commented
> Hey @PammyLo 😊 Just wanted to double check before approving - are the square brackets around the URLs expected? <img alt="Screenshot 2023-06-05 at 09 11 52" width="288" src="https://user-images.githubusercontent.com/87582782/243292393-b4ce1db3-a391-4320-af34-c3e93188e328.png">

Hi Cat, no the square brackets should be removed by this code. If you have AIRTABLE_PROJECTS_RESOURCES_CACHE_TABLE="Projects resources cache TEST"  in your .env then you will see that the change is made to the description in Airtable but that that your simulators pull the description from the table 'Projects resources cache'.  If you briefly change your .env to point at 'Projects resources cache' then you will see the changes in your build.

2023-06-06 13:55 UTC, joefhall requested changes
Top regex work @PammyLo! 👏 

Spotted a few little things if you can take a look

2023-06-06 13:55 UTC, joefhall commented on .github/workflows/ci_api.yml
> +          SLACK_SECRET_WEBHOOK_MY_AWESOME_CHANNEL: ${{ secrets.SLACK_SECRET_WEBHOOK_MY_AWESOME_CHANNEL}}
I don't think this needs to be included here?

2023-06-06 13:55 UTC, joefhall commented on api/cron-jobs/projects.js
> +require("dotenv").config();
I think your code editor has automatically reformatted lots of single quotes to double quotes so it's showing up with more changes than necessary -- these should all stay as single quotes as that's the code style here.  (We have [a ticket in the backlog to set proper coding style config for the API code](https://sta2020.atlassian.net/browse/SVA-293), which would help avoid this happening but we haven't done that yet.)

2023-06-06 13:55 UTC, joefhall commented on api/helpers/urls.js
> +    url ? url : ""
Tiny thing, but you could use a [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) (`??`) here so the line's a bit shorter and neater: `url ?? ''`

2023-06-06 13:55 UTC, joefhall commented on app/src/NativeBase/Components/List.tsx
> +                    <Hyperlink linkDefault={true} linkStyle={{ color: 'blue' }}>
Should this be a brand colour rather than a generic blue?  (Have you checked with Mia what colour she would like these links to be?)

2023-06-06 19:32 UTC, closed without merging