Sva 293 add es lint and prettier config to api directory
Scottish-Tech-Army/Volunteer-app pull request #192
Opened 2023-08-01 16:25 UTC by M4RC1N76

- [Description](#description)
 

# Description

- Added a prettierrc.json to the /api/ directory
- Added a eslintrc.js config file to the /api/ directory
- Have converted CommonJS require statements into ES6 import statements
- Have verified the code re-formats upon save with Prettier formatting, and when running npx eslint .  the linter runs correctly and provides errors. There will need to be a separate ticket to fix all issues in the linters, and some of the config rules might need updating depending on this.
- In the /api/ directory package.json, i've installed two additional dependencies, as I was having issues with eslint and prettier. Installing the plugin 'eslint-plugin-prettier' fixed these issues. (I suspect it is because i'm using Prettier v3.0, unlike the app directory which uses Prettier v2.8.8)
- Fixes # (SVA-293)

## Type of change

- [x] New Feature (non-breaking change which adds functionality)
- [x] Breaking change(fix or feature that would cause existing functionality to not work as expected)

# Testing locally

- Run `npm install` and ensure that Prettier works and run the command `npx eslint .` in the api directory to ensure that you can see the linting working. You should see 158 problems in the results. This is expected and need to be addressed in a separate ticket.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [ ] I have checked the app in dark mode, if making front-end design changes
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have updated the version numbers in `package.json` files in the [app](DEPLOYMENT.md#app-deployment) and/or [api](DEPLOYMENT.md#api-deployment-on-aws) directories as needed

2023-08-01 18:33 UTC, kelsiesmurphy commented
Commenting so i can get notified and answer any questions on the bits I did :)

2023-08-02 14:23 UTC, joefhall requested changes
Epic work @M4RC1N76 @kelsiesmurphy -- thanks a lot!

Have scanned through everything and looking good but can't guarantee I haven't missed anything, as obviously it's an enormous diff.

Have you been able to a) get the API running locally with these changes and b) get tests to pass?  Both are failing for me at the moment, though possible it's just small fixes that are needed to get these working.

Also spotted a few small things, please see questions/comments.

2023-08-02 14:23 UTC, joefhall commented on api/cron-jobs/projects.js
> +require('dotenv').config()
Same point as before that I think this can be updated to an `import` (please see earlier comment)

2023-08-02 14:23 UTC, joefhall commented on api/cron-jobs/projects.js
> +    await _addNewRecords(projectsResourcesCacheTable(), projectsResourcesChunk)
I didn't know about this underscore syntax, that's good to learn! 🔥

2023-08-02 14:23 UTC, joefhall commented on api/helpers/airTable.js
> +require('dotenv').config()
As above -- please see earlier comment

2023-08-02 14:23 UTC, joefhall commented on api/package.json
> +    "*.{js,ts,tsx, jsx}": [
I don't think we should be including `tsx` or `jsx` extensions here, as those are specifically for React

2023-08-02 14:23 UTC, joefhall commented on api/package.json
> +    "*.{json,md,html,js,jsx,ts,tsx}": [
As above about `tsx` and `jsx`

2023-08-02 14:23 UTC, joefhall commented on api/services/slack.js
> +require('dotenv').config()
As above - please see other comment

2023-08-03 09:07 UTC, joefhall commented
Hey @kelsiesmurphy @M4RC1N76 just to flag, I've merged my latest PR into `develop` now so you'll need to merge those latest changes into your PR here.  (Obviously no need to worry about the changes that were just formatting, but the updated functionality and tests are needed.)

2023-08-03 11:15 UTC, joefhall commented
Hi again @kelsiesmurphy @M4RC1N76 I think there's a solution to the problem you were having with imports.  Looking at this answer https://stackoverflow.com/a/59399717/15422951 

If you do option 1 you need to:
- add `"type": "module",` to api/package.json (at the top level below e.g. `"main": "app.js",`) -- this tells Node to treat files as modules by default
- all the import statements need to use `.js` in their filenames (e.g. `import { listen } from './app.js'`)

Alternatively you could do their option 2 and rename all the JS module files to .mjs which tells Node they are modules

I'm not certain which is easier.  Option 1 feels a bit neater?  Option 2 might be a quicker job?  Not sure what option 2 would do to the diff (hopefully GitHub will just see it as a filename change, not show the whole file in the PR?)  Option 2 might also work better if there are any JS files which shouldn't be treated as modules -- or is that all of them now anyway (including tests)?  If it is all of  them maybe option 1 is better.

2023-08-03 11:42 UTC, kelsiesmurphy commented
> Hi again @kelsiesmurphy @M4RC1N76 I think there's a solution to the problem you were having with imports. Looking at this answer https://stackoverflow.com/a/59399717/15422951
> 
> If you do option 1 you need to:
> 
> * add `"type": "module",` to api/package.json (at the top level below e.g. `"main": "app.js",`) -- this tells Node to treat files as modules by default
> * all the import statements need to use `.js` in their filenames (e.g. `import { listen } from './app.js'`)
> 
> Alternatively you could do their option 2 and rename all the JS module files to .mjs which tells Node they are modules
> 
> I'm not certain which is easier. Option 1 feels a bit neater? Option 2 might be a quicker job? Not sure what option 2 would do to the diff (hopefully GitHub will just see it as a filename change, not show the whole file in the PR?) Option 2 might also work better if there are any JS files which shouldn't be treated as modules -- or is that all of them now anyway (including tests)? If it is all of them maybe option 1 is better.

So I had already went down this path, and I started getting heaps of issues surrounding 'export default X' and the equivalent destructured 'import {X} from Y' routes. Some of the particular issues were around importing JSON into a file, which we do several times, and i think I started going around in circles with it. When I have an hour or two free i'll revisit it :)

2023-08-03 14:27 UTC, joefhall commented
Good luck with it!  It's pesky -- if we were using Typescript, it would be super simple _(one day...)_

You may well have seen this already, but just in case not: https://www.stefanjudis.com/snippets/how-to-import-json-files-in-es-modules-node-js/

2023-10-05 20:01 UTC, closed without merging