feature/sva-354-my-experience-profile-buttons
Scottish-Tech-Army/Volunteer-app pull request #194
Opened 2023-08-03 08:58 UTC by DJMF2015

- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description
- adds logic to toggle between 'Next' and 'Continue' buttons in MyExperiencsContainer and then hide 'Skip' button.
- 'Continue' button turns solid purple.
 
## Type of change

Please delete options that are not relevant
 
- [] New Feature (non-breaking change which adds functionality) 

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [x] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [x] I have checked the app in dark mode, if making front-end design changes
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x] I have updated the version numbers in `package.json` files in the [app](DEPLOYMENT.md#app-deployment) and/or [api](DEPLOYMENT.md#api-deployment-on-aws) directories as needed

2023-08-03 20:42 UTC, PammyLo requested changes
Great work David! @DJMF2015 

Thanks for adding the reusable components to the Readme file, that's very helpful :) 

The added button looks like the design (although I wonder what the intended effect of this button is?) - I just wanted to add here that the progress bar shouldn't move to the next section until the final 'continue' button is clicked as that is when the user progresses to the next stage of the registration. 

I've added a few other small questions/suggestions in the code.

2023-08-03 20:42 UTC, PammyLo commented on APP_DEVELOPMENT.md
> +- [App development](#app-development)
I don't think it needs a link to the App development section as we're already here ;)

2023-08-03 20:42 UTC, PammyLo commented on APP_DEVELOPMENT.md
> +STA Matchstick Logo with seven, rotated multi-coloured matchsticks
I can see where you're coming from but this is actually a logo, not a component and doesn't belong here. I think other developers would be able to find this in the logos as that would probably the place where anyone would look for it.

2023-08-03 20:42 UTC, PammyLo commented on APP_DEVELOPMENT.md
> +
Great additions David! Well done on adding three reusable components, awesome :) 

It looks like the naming convention here is to add the reference to the components here with the name as it is in the code, i.e. StaRibbon, Checkbox, ProgressBar.

2023-08-03 20:42 UTC, PammyLo commented on app/src/Assets/Images/Checkbox Group.jpg
It looks like the other screenshots of reusable components are all in the folder: 
 `/Volunteer-app/screenshots/components`

2023-08-14 13:31 UTC, M4RC1N76 commented
Hi @DJMF2015  David, I have tested the functionality of the 'Next' button in the 'My Experience' section. It works great!! After I have selected Web Developer from the list I am taken to the next screen when I can see 'Done' button (in solid purple). The 'Skip' button is gone by then. I can't seem to find 'Continue' button. on neither of the screens, could you advise on that, please? I am using my Samsung (physical) phone.

2023-08-14 13:49 UTC, DJMF2015 commented
Hi @M4RC1N76 . It should display 'Done' and not 'Continue' when you see press the button as Joanna wanted me to change this. She also asked me to comment the progress bar out. Does that make sense?

2023-08-14 13:52 UTC, M4RC1N76 commented
Thanks David, that make sense now. Everything works great!!

2023-08-14 13:52 UTC, M4RC1N76 approved these changes
Everything works great!!

2023-09-04 11:57 UTC, PammyLo approved these changes

2023-09-04 14:57 UTC, merged