Adds feature flags hook
Scottish-Tech-Army/Volunteer-app pull request #206
Opened 2023-11-08 12:50 UTC by roryf

# Description

Adds `useFeatureFlags` hook to easily enable and disable features in the app based on environment variables. This will enable us to continuously build and release changes without long lived feature branches.

This is a very basic feature flag implementation based on an environment variable `FEATURES_ENABLED` which has been added to `.env.example`, but it allows us to turn on features locally and in a future "Canary" app build whilst having the code merged and released to production with feature turned off. Other hosted options give more flexibility but come at a cost 💵 

Once merged, we can attempt a build and release to app stores which will get code in the wild along with some other improvements that have been merged since last release, without adding unfinished features.

**Expo limitations**

Since this uses an environment variable, which is only loaded once when the Expo cli is started (`npm run start`), changing the value will require restarting expo cli and Expo Go on simulator. In practice we shouldn't be changing this much during development, except to add a new feature flag, so this should only cause pain during initial testing.

## Type of change

Please delete options that are not relevant

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Testing locally

Update your `.env` file with suggested `FEATURES_ENABLED` from `.env.example`, restart Expo cli and Expo Go, verify `Profile` and `Events` tabs appear in bottom nav.

Remove `FEATURES_ENABLED` from `.env` (or make it's value empty), restart Expo cli and Expo Go, verify `Profile` and `Events` tabs **do not** appear in bottom nav. This is the config that we will initially release to app stores.

# Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] I have updated the version numbers in `package.json` files in the [app](DEPLOYMENT.md#app-deployment) and/or [api](DEPLOYMENT.md#api-deployment-on-aws) directories as needed

2023-12-04 20:09 UTC, DougieWougie requested changes
Couple of conflicts to resolve @roryf after merging 205

2023-12-05 13:33 UTC, roryf commented
@DougieWougie fixed

2023-12-05 13:36 UTC, DougieWougie approved these changes

2023-12-05 13:39 UTC, M4RC1N76 approved these changes
Great work @roryf !!  @DougieWougie thanks for your help !!

2023-12-05 13:42 UTC, merged