Bug/sva 65
Scottish-Tech-Army/Volunteer-app pull request #22
Opened 2021-09-12 14:01 UTC by Boopster

2021-09-13 09:04 UTC, mikemherron requested changes
I think we might need to add api/node_modules to gitignore? Looks like they have been checked in for the API folder.

2021-09-13 11:25 UTC, Boopster commented
> I think we might need to add api/node_modules to gitignore? Looks like they have been checked in for the API folder.

I think this is now resolved.

2021-09-14 21:08 UTC, mikemherron approved these changes

2021-09-14 21:11 UTC, CatMac228 approved these changes
Happy to approve :)

2021-09-14 21:22 UTC, CatMac228 approved these changes

2021-09-14 21:35 UTC, merged