Sva 219 welcome info only show on first use of the app
Scottish-Tech-Army/Volunteer-app pull request #96
Opened 2022-10-04 18:17 UTC by DougieWougie

- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description
- Added option to show/not show welcome screen
- Added reducers and amended store
- Buttons change colour to indicate state
- **Note the error at the top of the screen is a separate bug (#93)**

<img src="https://user-images.githubusercontent.com/25683216/193894791-a811a433-72fd-495c-bd41-d1e7d4650493.png" width="200px" />
## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an issue)
- [X] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-10-08 15:06 UTC, joefhall requested changes
Nice work @DougieWougie!  Works well -- and definitely a handy feature to have while we're developing the app 🙂  Just spotted a few small things.

2022-10-08 17:45 UTC, DougieWougie commented on app/src/Containers/WelcomeContainer.tsx
> +import {Dimensions, I18nManager, Platform, SafeAreaView, StyleSheet, View} from 'react-native'
Good spot. I need to change by default VS Code colour scheme - the bluish grey looks the same!

2022-10-08 17:53 UTC, DougieWougie commented
> Nice work @DougieWougie! Works well -- and definitely a handy feature to have while we're developing the app 🙂 Just spotted a few small things.

Thanks @joefhall - appreciated!

2022-10-10 07:35 UTC, joefhall approved these changes
Thanks @DougieWougie 🙌

2022-10-19 17:10 UTC, g-dunlop approved these changes
Works perfectly for me @DougieWougie. Nice one!

2022-10-20 19:45 UTC, merged